IF NOT EXISTS (
    select * from sysobjects where name='question DB' and xtype='U'
) CREATE TABLE question_DB (
    [class] NVARCHAR(10),
    [type] NVARCHAR(9),
    [method] NVARCHAR(15)
);
INSERT INTO question_DB VALUES
    (N'Object',N'Object',N'clone()'),
    (N'Object',N'boolean',N'equals(obj)'),
    (N'Object',N'void',N'finalize()'),
    (N'Object',N'Class',N'getClass()'),
    (N'Object',N'int',N'hashcode()'),
    (N'Object',N'String',N'toString()'),
    (N'Object',N'void',N'notify()'),
    (N'Object',N'void',N'nofigyAll()'),
    (N'Object',N'void',N'wait()'),
    (N'Object',N'void',N'wait(long)'),
    (N'String',N'String',N'String s'),
    (N'String',N'String',N'char[] value'),
    (N'String',N'char',N'charAt(int)'),
    (N'String',N'int',N'compareTo(str)'),
    (N'String',N'String',N'concat(str)'),
    (N'String',N'boolean',N'contains(str)'),
    (N'String',N'String',N'endsWith(str)'),
    (N'String',N'boolean',N'equals(obj)'),
    (N'String',N'int',N'indexOf(int)'),
    (N'String',N'int',N'indexOf(str)'),
    (N'String',N'String',N'intern()'),
    (N'String',N'int',N'length()'),
    (N'String',N'String',N'[] split(str)'),
    (N'String',N'boolean',N'startsWith(str)'),
    (N'String',N'String',N'substring(int)'),
    (N'String',N'String',N'toLowerCase()'),
    (N'String',N'String',N'toString()'),
    (N'String',N'String',N'toUpperCase()'),
    (N'String',N'String',N'trim()'),
    (N'Math',N'number',N'abs(num)'),
    (N'Math',N'double',N'ceil(dou)'),
    (N'Math',N'double',N'floor(dou)'),
    (N'Math',N'number',N'max(num, num)'),
    (N'Math',N'number',N'min(num, num)'),
    (N'Math',N'double',N'random()'),
    (N'Math',N'double',N'rint(dou)'),
    (N'Math',N'double',N'round(dou)'),
    (N'Math',N'double',N'round(flo)'),
    (N'JFrame',N'void',N'frameInit()'),
    (N'JFrame',N'Component',N'getGlassPane()'),
    (N'JFrame',N'Graphics',N'getGraphics()'),
    (N'JFrame',N'JMenuBar',N'getJMenuBar()'),
    (N'JFrame',N'JRootPane',N'getRootPane()'),
    (N'JFrame',N'String',N'paramString()'),
    (N'JFrame',N'void',N'remove'),
    (N'JFrame',N'void',N'repaint'),
    (N'JFrame',N'void',N'setContentPane'),
    (N'JFrame',N'void',N'setGlassPane'),
    (N'JFrame',N'void',N'setIconImage'),
    (N'JFrame',N'void',N'setJMenuBar'),
    (N'JFrame',N'void',N'setLayeredPane'),
    (N'JFrame',N'void',N'setLayout'),
    (N'JFrame',N'void',N'setRootPane'),
    (N'JFrame',N'void',N'update'),
    (N'JLabel',N'Icon',N'getIcon()'),
    (N'JLabel',N'Component',N'getLabelFor()'),
    (N'JLabel',N'String',N'getText()'),
    (N'JLabel',N'LabelUI',N'getUI()'),
    (N'JLabel',N'String',N'getUIClassID()'),
    (N'JLabel',N'boolean',N'imageUpdate'),
    (N'JLabel',N'String',N'paramString()'),
    (N'JLabel',N'void',N'setDisabledIcon'),
    (N'JLabel',N'void',N'setIcon'),
    (N'JLabel',N'void',N'setIconTextGap'),
    (N'JLabel',N'void',N'setLabelFor'),
    (N'JLabel',N'void',N'setText'),
    (N'JLabel',N'void',N'setUI'),
    (N'JLabel',N'void',N'updateUI()'),
    (N'Jbutton',N'String',N'getUIClassID()'),
    (N'Jbutton',N'String',N'paramString()'),
    (N'Jbutton',N'void',N'removeNotify()'),
    (N'Jbutton',N'void',N'updateUI()'),
    (N'JTextArea',N'int',N'getColumns()'),
    (N'JTextArea',N'int',N'getLineCount()'),
    (N'JTextArea',N'int',N'getLineOfOffset'),
    (N'JTextArea',N'boolean',N'getLineWrap()'),
    (N'JTextArea',N'int',N'getRowHeight()'),
    (N'JTextArea',N'int',N'getRows()'),
    (N'JTextArea',N'int',N'getTabSize()'),
    (N'JTextArea',N'String',N'getUIClassID()'),
    (N'JTextArea',N'void',N'insert'),
    (N'JTextArea',N'String',N'paramString'),
    (N'JTextArea',N'void',N'replaceRange'),
    (N'JTextArea',N'void',N'setColumns'),
    (N'JTextArea',N'void',N'setFont'),
    (N'JTextArea',N'void',N'setLineWrap'),
    (N'JTextArea',N'void',N'setRows'),
    (N'JTextArea',N'void',N'setTabSize'),
    (N'JTextField',N'Action',N'getAction()'),
    (N'JTextField',N'Action[]',N'getActions()'),
    (N'JTextField',N'int',N'getColumns()'),
    (N'JTextField',N'String',N'getUIClassID()'),
    (N'JTextField',N'String',N'paramString()'),
    (N'JTextField',N'void',N'setAction'),
    (N'JTextField',N'void',N'setColumns'),
    (N'JTextField',N'void',N'setDocument'),
    (N'JTextField',N'void',N'setFont'),
    (N'JTextField',N'void',N'setScrollOffset');
